import { LessonTopic, CategorizedLessons } from './types';

const GENERAL_LESSON_TOPICS: LessonTopic[] = [
  { english: "A Day at the Office", japanese: "オフィスでの一日" },
  { english: "Booking a Business Trip", japanese: "出張の予約" },
  { english: "Networking at a Conference", japanese: "カンファレンスでのネットワーキング" },
  { english: "Discussing a Marketing Strategy", japanese: "マーケティング戦略の議論" },
  { english: "Preparing for a Job Interview", japanese: "就職面接の準備" },
  { english: "Planning a Vacation", japanese: "休暇の計画" },
  { english: "Checking into a Hotel", japanese: "ホテルへのチェックイン" },
  { english: "Exploring a New City", japanese: "新しい都市の探索" },
  { english: "Dining at a Restaurant Abroad", japanese: "海外のレストランでの食事" },
  { english: "Shopping for Souvenirs", japanese: "お土産の買い物" },
  { english: "A Casual Chat with a Friend", japanese: "友人との気軽な会話" },
  { english: "Making Weekend Plans", japanese: "週末の計画を立てる" },
  { english: "Talking About Hobbies", japanese: "趣味について話す" },
  { english: "Cooking a Meal Together", japanese: "一緒に食事を作る" },
  { english: "A Family Gathering", japanese: "家族の集まり" },
  { english: "The History of the Internet", japanese: "インターネットの歴史" },
  { english: "Ancient Civilizations", japanese: "古代文明" },
  { english: "The Renaissance Period", japanese: "ルネサンス期" },
  { english: "World War II Key Events", japanese: "第二次世界大戦の主要な出来事" },
  { english: "The Space Race", japanese: "宇宙開発競争" },
  { english: "Introduction to Quantum Physics", japanese: "量子物理学入門" },
  { english: "The Human Brain", japanese: "人間の脳" },
  { english: "Climate Change and its Effects", japanese: "気候変動とその影響" },
  { english: "The Process of Photosynthesis", japanese: "光合成のプロセス" },
  { english: "Exploring the Solar System", japanese: "太陽系の探査" },
  { english: "Project Management Basics", japanese: "プロジェクト管理の基礎" },
  { english: "Negotiating a Contract", japanese: "契約交渉" },
  { english: "Giving a Presentation", japanese: "プレゼンテーションを行う" },
  { english: "Handling Customer Complaints", japanese: "顧客からの苦情対応" },
  { english: "Team Building Activities", japanese: "チームビルディング活動" },
  { english: "Going Through Airport Security", japanese: "空港のセキュリティチェック" },
  { english: "Renting a Car", japanese: "レンタカーを借りる" },
  { english: "Asking for Directions", japanese: "道を尋ねる" },
  { english: "Using Public Transportation", japanese: "公共交通機関の利用" },
  { english: "Dealing with Lost Luggage", japanese: "紛失した荷物の対処" },
  { english: "Visiting a Doctor", japanese: "医者に行く" },
  { english: "A Trip to the Supermarket", japanese: "スーパーマーケットへの買い物" },
  { english: "Discussing Movies and TV Shows", japanese: "映画やテレビ番組について話す" },
  { english: "Planning a Party", japanese: "パーティーの計画" },
  { english: "Talking About a Book", japanese: "本について話す" },
  { english: "The Industrial Revolution", japanese: "産業革命" },
  { english: "The Roaring Twenties", japanese: "狂騒の20年代" },
  { english: "The Cold War Era", japanese: "冷戦時代" },
  { english: "The Discovery of America", japanese: "アメリカ大陸の発見" },
  { english: "The French Revolution", japanese: "フランス革命" },
  { english: "The Theory of Relativity", japanese: "相対性理論" },
  { english: "The Basics of Genetics", japanese: "遺伝学の基礎" },
  { english: "Marine Biology", japanese: "海洋生物学" },
  { english: "The Earth's Ecosystems", japanese: "地球の生態系" },
  { english: "Volcanoes and Earthquakes", japanese: "火山と地震" },
  { english: "Financial Planning for Retirement", japanese: "退職後のためのファイナンシャルプランニング" },
  { english: "Understanding the Stock Market", japanese: "株式市場を理解する" },
  { english: "Email Etiquette in Business", japanese: "ビジネスにおけるEメールのエチケット" },
  { english: "Leading a Team Meeting", japanese: "チームミーティングの主導" },
  { english: "Performance Reviews", japanese: "業績評価" },
  { english: "Cultural Differences in Tourism", japanese: "観光における文化の違い" },
  { english: "Sustainable Travel", japanese: "持続可能な旅行" },
  { english: "Staying at a Bed and Breakfast", japanese: "B&B（民宿）に滞在する" },
  { english: "Adventure Travel Experiences", japanese: "アドベンチャートラベル体験" },
  { english: "Attending a Music Festival", japanese: "音楽フェスティバルに参加する" },
  { english: "Volunteering in the Community", japanese: "地域社会でのボランティア活動" },
  { english: "Joining a Fitness Class", japanese: "フィットネスクラスに参加する" },
  { english: "Discussing Current Events", japanese: "時事問題について議論する" },
  { english: "Home Improvement Projects", japanese: "家のリフォームプロジェクト" },
  { english: "Adopting a Pet", japanese: "ペットを飼う" },
  { english: "The History of Art", japanese: "美術の歴史" },
  { english: "Famous Inventors and Their Inventions", japanese: "有名な発明家とその発明品" },
  { english: "The Rise and Fall of the Roman Empire", japanese: "ローマ帝国の興亡" },
  { english: "The Silk Road", japanese: "シルクロード" },
  { english: "The Digital Age", japanese: "デジタル時代" },
  { english: "Artificial Intelligence Explained", japanese: "人工知能の解説" },
  { english: "The Importance of Biodiversity", japanese: "生物多様性の重要性" },
  { english: "Renewable Energy Sources", japanese: "再生可能エネルギー源" },
  { english: "The Science of Sleep", japanese: "睡眠の科学" },
  { english: "Nutrition and a Healthy Diet", japanese: "栄養と健康的な食事" },
  { english: "Corporate Social Responsibility", japanese: "企業の社会的責任（CSR）" },
  { english: "E-commerce Trends", japanese: "Eコマースのトレンド" },
  { english: "Writing a Business Proposal", japanese: "ビジネス提案書の作成" },
  { english: "Conflict Resolution in the Workplace", japanese: "職場での対立解決" },
  { english: "Time Management Techniques", japanese: "時間管理術" },
  { english: "Packing for a Long Trip", japanese: "長期旅行の荷造り" },
  { english: "Navigating a Foreign Country's Customs", japanese: "外国の税関を通過する" },
  { english: "Learning a New Language for Travel", japanese: "旅行のために新しい言語を学ぶ" },
  { english: "Travel Blogging", japanese: "旅行ブログ" },
  { english: "Eco-tourism", japanese: "エコツーリズム" },
  { english: "Organizing a Neighborhood Watch", japanese: "地域防犯組織の設立" },
  { english: "Debating a Social Issue", japanese: "社会問題について討論する" },
  { english: "The Joy of Gardening", japanese: "ガーデニングの喜び" },
  { english: "Sharing Personal Goals", japanese: "個人的な目標を共有する" },
  { english: "Moving to a New House", japanese: "新しい家への引っ越し" },
  { english: "The Age of Exploration", japanese: "大航海時代" },
  { english: "The Reformation", japanese: "宗教改革" },
  { english: "The Victorian Era", japanese: "ヴィクトリア朝時代" },
  { english: "The Civil Rights Movement", japanese: "公民権運動" },
  { english: "The Roaring Twenties in America", japanese: "アメリカの狂騒の20年代" },
  { english: "The Future of Space Exploration", japanese: "宇宙探査の未来" },
  { english: "Understanding Black Holes", japanese: "ブラックホールの理解" },
  { english: "The Psychology of Decision Making", japanese: "意思決定の心理学" },
  { english: "How Vaccines Work", japanese: "ワクチンの仕組み" },
  { english: "The Wonders of the Deep Sea", japanese: "深海の驚異" }
];

const BUSINESS_LESSON_TOPICS: LessonTopic[] = [
    { english: "A Weekly Team Sync-up", japanese: "週次のチーム同期会議" },
    { english: "Brainstorming for a New Product with a Colleague", japanese: "同僚との新製品ブレインストーミング" },
    { english: "Leading a Project Kick-off Meeting", japanese: "プロジェクトキックオフ会議の主導" },
    { english: "Presenting Quarterly Results to the Team", japanese: "チームへの四半期業績プレゼンテーション" },
    { english: "Handling a Customer Complaint over the Phone", japanese: "電話での顧客からの苦情対応" },
    { english: "Asking a Colleague for Help with a Task", japanese: "同僚に仕事の助けを求める" },
    { english: "Giving a Performance Review", japanese: "業績評価の実施" },
    { english: "Participating in a Conference Call with Clients", japanese: "クライアントとの電話会議への参加" },
    { english: "Networking at a Business Mixer", japanese: "ビジネス交流会でのネットワーキング" },
    { english: "Requesting a Deadline Extension from a Manager", japanese: "マネージャーへの締め切り延長の要請" },
    { english: "Planning a team lunch", japanese: "チームランチの計画" },
    { english: "Delegating Tasks to a Team Member", japanese: "チームメンバーへのタスクの委任" },
    { english: "Scheduling a Meeting via Email with the Team", japanese: "チームとのメールでの会議日程調整" },
    { english: "Resolving a Conflict Between Colleagues", japanese: "同僚間の対立解決" },
    { english: "Onboarding a New Employee", japanese: "新入社員のオンボーディング" },
    { english: "Making Small Talk with a Client Before a Meeting", japanese: "会議前のクライアントとの雑談" },
    { english: "Pitching an Idea to Management", japanese: "経営陣へのアイデアの売り込み" },
    { english: "Discussing the Annual Budget", japanese: "年間予算についての議論" },
    { english: "Following Up with a Potential Client", japanese: "見込み客へのフォローアップ" },
    { english: "Asking for Feedback on a Proposal from a Teammate", japanese: "チームメイトからの提案書へのフィードバックを求める" },
    { english: "Arranging a Business Lunch with a Partner Company", japanese: "提携企業とのビジネスランチの手配" },
    { english: "Troubleshooting a Technical Problem Together", japanese: "技術的な問題を一緒にトラブルシューティングする" },
    { english: "Explaining a Company Policy Change to a Colleague", japanese: "同僚への会社方針の変更説明" },
    { english: "Negotiating a Sales Contract", japanese: "販売契約の交渉" },
    { english: "Celebrating a Team's Success", japanese: "チームの成功を祝う" },
    { english: "Catching up after the weekend with coworkers", japanese: "週末明けに同僚と近況を話す" },
    { english: "Discussing a Marketing Campaign's Progress", japanese: "マーケティングキャンペーンの進捗に関する議論" },
    { english: "Clarifying Responsibilities on a Project", japanese: "プロジェクトにおける責任の明確化" },
    { english: "Handling an Urgent Request from a Client", japanese: "クライアントからの緊急依頼への対応" },
    { english: "Debriefing with a colleague after a client meeting", japanese: "クライアント会議の後に同僚と状況を整理する" },
    { english: "Providing Constructive Criticism to a Peer", japanese: "同僚への建設的な批判の提供" },
    { english: "Apologizing to a Colleague for a Mistake", japanese: "同僚へのミスに対する謝罪" },
    { english: "Discussing CSR Initiatives in a team meeting", japanese: "チーム会議でのCSR活動に関する議論" },
    { english: "Planning a Company Offsite Event", japanese: "社外イベントの計画" },
    { english: "Talking to HR about Benefits", japanese: "人事部と福利厚生について話す" },
    { english: "Sharing feedback on a shared document", japanese: "共有ドキュメントに関するフィードバックの共有" },
    { english: "Setting Personal Goals with a Mentor", japanese: "メンターとの個人目標設定" },
    { english: "A Mentoring Session with a Junior Colleague", japanese: "後輩社員とのメンタリングセッション" },
    { english: "Cross-cultural Communication in a Global Team Call", japanese: "グローバルチームの電話会議における異文化コミュニケーション" },
    { english: "Managing a Project Budget with the Finance Team", japanese: "財務チームとのプロジェクト予算管理" },
    { english: "Updating Stakeholders on Project Progress", japanese: "利害関係者へのプロジェクト進捗報告" },
    { english: "Debating a Strategic Decision in a Team Meeting", japanese: "チーム会議での戦略的決定に関する討論" },
    { english: "A Sales Training Role-play with a Colleague", japanese: "同僚との営業研修ロールプレイング" },
    { english: "A casual chat by the coffee machine", japanese: "コーヒーメーカーのそばでの雑談" },
    { english: "Requesting New Equipment or Software", japanese: "新しい機材やソフトウェアの要求" },
    { english: "Introducing a New Team Member to the department", japanese: "部署への新しいチームメンバーの紹介" },
    { english: "Discussing Cybersecurity Measures with IT", japanese: "IT部門とのサイバーセキュリティ対策に関する議論" },
    { english: "A Farewell Conversation with a Departing Colleague", japanese: "退職する同僚との別れの会話" },
    { english: "Negotiating Work-from-Home Arrangements", japanese: "在宅勤務の取り決めに関する交渉" },
    { english: "Giving a handover before going on leave", japanese: "休暇に入る前の引き継ぎ" },
    { english: "Talking about Industry Trends with a Teammate", japanese: "チームメイトと業界の動向について話す" },
    { english: "Checking in on a Colleague's Well-being", japanese: "同僚の安否確認" },
    { english: "Persuading a Skeptical Manager", japanese: "懐疑的なマネージャーの説得" },
    { english: "Explaining a complex process to a teammate", japanese: "チームメイトへの複雑なプロセスの説明" },
    { english: "A Customer Service Follow-up Call", japanese: "カスタマーサービスのフォローアップ電話" },
    { english: "Collaborating on a Presentation with a Colleague", japanese: "同僚とのプレゼンテーションでの共同作業" },
    { english: "Giving a Tour of the Office to a New Client", japanese: "新規クライアントへのオフィスツアー" },
    { english: "Discussing KPIs in a team review", japanese: "チームレビューでのKPIに関する議論" },
    { english: "Coordinating vacation schedules with the team", japanese: "チームとの休暇スケジュールの調整" },
    { english: "Brainstorming Ways to Improve Team Efficiency", japanese: "チームの効率を改善する方法のブレインストーミング" },
    { english: "Outlining a Project Plan with a Partner", japanese: "パートナーとのプロジェクト計画の概要説明" },
    { english: "Dealing with a Micromanaging Boss", japanese: "マイクロマネジメントする上司への対処" },
    { english: "Finalizing a Product Launch Plan", japanese: "製品発売計画の最終決定" },
    { english: "Discussing weekend plans on a Friday afternoon", japanese: "金曜の午後に週末の計画を話す" },
    { english: "Discussing Market Research Findings", japanese: "市場調査結果に関する議論" },
    { english: "Making plans for after-work drinks", japanese: "仕事後の飲み会の計画を立てる" },
    { english: "Interviewing a Candidate for a Technical Role", japanese: "技術職候補者の面接" },
    { english: "Requesting a Leave of Absence", japanese: "休職の申請" },
    { english: "Mediating a Disagreement on a Project", japanese: "プロジェクトでの意見の相違の仲裁" },
    { english: "A Performance Improvement Plan Discussion", japanese: "業績改善計画に関する話し合い" },
    { english: "Welcoming a Colleague Back from Leave", japanese: "休暇から戻った同僚を迎える" },
    { english: "Talking about Supply Chain Issues with a vendor", japanese: "ベンダーとのサプライチェーン問題に関する議論" },
    { english: "Pitching a new Marketing Slogan to the team", japanese: "チームへの新しいマーケティングスローガンの提案" },
    { english: "Offering help to a colleague who seems overwhelmed", japanese: "忙殺されている同僚に助けを申し出る" },
    { english: "A Town Hall Meeting with the CEO", japanese: "CEOとのタウンホールミーティング" },
    { english: "Reviewing a presentation draft together", japanese: "プレゼンテーションの下書きを一緒に確認する" },
    { english: "Discussing a new Software Implementation", japanese: "新しいソフトウェア導入に関する議論" },
    { english: "A Business Ethics Discussion", japanese: "ビジネス倫理に関する議論" },
    { english: "Training a Junior Employee", japanese: "若手社員のトレーニング" },
    { english: "Reviewing Customer Feedback", japanese: "顧客からのフィードバックのレビュー" },
    { english: "Setting up an Informational Interview", japanese: "情報収集のための面接の設定" },
    { english: "Politely Declining a Request from a Colleague", japanese: "同僚からの依頼を丁寧に断る" },
    { english: "Summarizing Action Items at the End of a Meeting", japanese: "会議の終わりにアクションアイテムを要約する" },
    { english: "Talking to a Vendor about a Billing Error", japanese: "請求エラーについてベンダーと話す" },
    { english: "Rehearsing a Presentation with a Colleague", japanese: "同僚とプレゼンテーションのリハーサル" },
    { english: "Discussing Employee Engagement Survey Results", japanese: "従業員エンゲージメント調査結果に関する議論" },
    { english: "Planning a Trade Show Booth", japanese: "展示会ブースの計画" },
    { english: "Brainstorming a Company's Mission Statement", japanese: "会社のミッションステートメントのブレインストーミング" },
    { english: "Deciding who will handle a new incoming task", japanese: "新しいタスクの担当者を決める" },
    { english: "A Project Post-mortem Meeting", japanese: "プロジェクトの事後検討会" },
    { english: "Discussing Health and Safety in the Workplace", japanese: "職場における健康と安全に関する議論" },
    { english: "Asking for a Raise", japanese: "昇給を求める" },
    { english: "Sharing interesting industry news with a coworker", japanese: "同僚と興味深い業界ニュースを共有する" },
    { english: "Finalizing the Agenda for a Team Meeting", japanese: "チームミーティングのアジェンダの最終決定" },
    { english: "Asking for a colleague's opinion on an email draft", japanese: "メールの下書きについて同僚の意見を求める" },
    { english: "Conducting a SWOT Analysis with the team", japanese: "チームでのSWOT分析の実施" },
    { english: "A Professional Development Planning Session", japanese: "専門能力開発計画セッション" },
    { english: "Providing a Reference for a Former Colleague", japanese: "元同僚の推薦状を提供する" },
    { english: "Discussing a Change in Company Strategy", japanese: "会社戦略の変更に関する議論" },
    { english: "Greeting a Visitor at the Office", japanese: "オフィスでの訪問者の出迎え" },
];

const DAILY_LESSON_TOPICS: LessonTopic[] = [
  { english: "Ordering Coffee", japanese: "コーヒーを注文する" },
  { english: "Asking for Directions", japanese: "道を尋ねる" },
  { english: "Buying Groceries", japanese: "食料品を買う" },
  { english: "Making a Dinner Reservation", japanese: "ディナーの予約をする" },
  { english: "Talking About the Weather", japanese: "天気について話す" },
  { english: "A Casual Chat with a Neighbor", japanese: "隣人との気軽な会話" },
  { english: "Planning a Weekend Trip with Friends", japanese: "友人との週末旅行の計画" },
  { english: "At the Doctor's Office", japanese: "病院の診察室にて" },
  { english: "Getting a Haircut", japanese: "散髪する" },
  { english: "Returning an Item to a Store", japanese: "お店に商品を返品する" },
  { english: "Taking a Taxi", japanese: "タクシーに乗る" },
  { english: "At the Airport Check-in", japanese: "空港のチェックインにて" },
  { english: "Going Through Security at the Airport", japanese: "空港のセキュリティを通過する" },
  { english: "Ordering Food on a Plane", japanese: "飛行機で食べ物を注文する" },
  { english: "Checking into a Hotel", japanese: "ホテルにチェックインする" },
  { english: "Asking for Housekeeping Services", japanese: "ハウスキーピングを頼む" },
  { english: "Checking out of a Hotel", japanese: "ホテルをチェックアウトする" },
  { english: "Renting a Car", japanese: "レンタカーを借りる" },
  { english: "Buying Train Tickets", japanese: "電車のチケットを買う" },
  { english: "At the Post Office", japanese: "郵便局にて" },
  { english: "Opening a Bank Account", japanese: "銀行口座を開設する" },
  { english: "Reporting a Lost Credit Card", japanese: "クレジットカードの紛失を届け出る" },
  { english: "At the Pharmacy", japanese: "薬局にて" },
  { english: "Discussing a Movie You Just Watched", japanese: "観たばかりの映画について話す" },
  { english: "Making Plans for Dinner", japanese: "夕食の計画を立てる" },
  { english: "Inviting a Friend Over", japanese: "友人を家に招待する" },
  { english: "Talking About Your Family", japanese: "家族について話す" },
  { english: "Discussing Your Job", japanese: "自分の仕事について話す" },
  { english: "Talking About Hobbies and Interests", japanese: "趣味や興味について話す" },
  { english: "A Phone Call with a Friend", japanese: "友人との電話" },
  { english: "Leaving a Voicemail", japanese: "留守番電話にメッセージを残す" },
  { english: "Joining a Gym", japanese: "ジムに入会する" },
  { english: "At the Library", japanese: "図書館にて" },
  { english: "A Parent-Teacher Conference", japanese: "保護者面談" },
  { english: "Meeting a Friend's Partner for the First Time", japanese: "友人のパートナーに初めて会う" },
  { english: "Congratulating Someone", japanese: "誰かをお祝いする" },
  { english: "Offering Condolences", japanese: "お悔やみを言う" },
  { english: "Complimenting Someone", japanese: "誰かを褒める" },
  { english: "Asking for a Favor", japanese: "お願い事をする" },
  { english: "Apologizing for Being Late", japanese: "遅刻したことを謝る" },
  { english: "A Barbecue with Friends", japanese: "友人とのバーベキュー" },
  { english: "At a Birthday Party", japanese: "誕生日パーティーにて" },
  { english: "Discussing a Book You're Reading", japanese: "読んでいる本について話す" },
  { english: "Talking About Your Favorite Music", japanese: "好きな音楽について話す" },
  { english: "Planning a Potluck Dinner", japanese: "持ち寄りディナーの計画" },
  { english: "Visiting a Museum", japanese: "美術館を訪れる" },
  { english: "At a Gas Station", japanese: "ガソリンスタンドにて" },
  { english: "Dealing with a Power Outage", japanese: "停電に対処する" },
  { english: "Talking to a Landlord about a Repair", japanese: "大家に修理について話す" },
  { english: "Getting Your Car Repaired", japanese: "車の修理をしてもらう" },
  { english: "A First Date", japanese: "初めてのデート" },
  { english: "Discussing Current Events", japanese: "時事問題について話す" },
  { english: "Volunteering for a Cause", japanese: "社会貢献活動のボランティア" },
  { english: "Attending a Wedding", japanese: "結婚式に出席する" },
  { english: "Buying a Piece of Furniture", japanese: "家具を買う" },
  { english: "Hiring a Plumber", japanese: "配管工を雇う" },
  { english: "A visit to the dentist", japanese: "歯医者に行く" },
  { english: "Discussing exercise routines", japanese: "運動習慣について話す" },
  { english: "Making a complaint about a noisy neighbor", japanese: "騒がしい隣人について苦情を言う" },
  { english: "Planning a surprise party", japanese: "サプライズパーティーを計画する" },
  { english: "Asking for restaurant recommendations", japanese: "おすすめのレストランを尋ねる" },
  { english: "Talking about childhood memories", japanese: "子供の頃の思い出を話す" },
  { english: "A conversation with a pet owner", japanese: "ペットの飼い主との会話" },
  { english: "Discussing holiday plans", japanese: "休暇の計画について話す" },
  { english: "Giving advice to a friend", japanese: "友人にアドバイスをする" },
  { english: "At a farmers' market", japanese: "ファーマーズマーケットにて" },
  { english: "Learning a new skill", japanese: "新しいスキルを学ぶ" },
  { english: "Renewing a driver's license", japanese: "運転免許を更新する" },
  { english: "Discussing a news article", japanese: "ニュース記事について議論する" },
  { english: "Ordering pizza for delivery", japanese: "ピザの配達を注文する" },
  { english: "A conversation at a dog park", japanese: "ドッグパークでの会話" },
  { english: "Talking about a recent vacation", japanese: "最近の休暇について話す" },
  { english: "Catching up with an old friend", japanese: "旧友と近況を語り合う" },
  { english: "Helping a tourist with directions", japanese: "観光客に道を教える" },
  { english: "A coffee break conversation", japanese: "コーヒーブレイクでの会話" },
  { english: "Explaining how to use a new app", japanese: "新しいアプリの使い方を説明する" },
  { english: "At a flea market", japanese: "フリーマーケットにて" },
  { english: "Discussing different types of cuisine", japanese: "様々な種類の料理について話す" },
  { english: "Planning a hiking trip", japanese: "ハイキングの計画を立てる" },
  { english: "A conversation about a favorite TV show", japanese: "好きなテレビ番組についての会話" },
  { english: "At a job fair", japanese: "就職フェアにて" },
  { english: "Discussing home decoration ideas", japanese: "家の装飾のアイデアについて話す" },
  { english: "Getting advice on what to wear to an event", japanese: "イベントに着ていく服のアドバイスをもらう" },
  { english: "A conversation about saving money", japanese: "節約についての会話" },
  { english: "Dealing with a lost-and-found item", japanese: "遺失物取扱所でのやり取り" },
  { english: "At a hardware store", japanese: "ホームセンターにて" },
  { english: "Discussing gardening tips", japanese: "ガーデニングのコツについて話す" },
  { english: "A conversation about healthy eating habits", japanese: "健康的な食生活についての会話" },
  { english: "Making plans to see a play", japanese: "観劇の計画を立てる" },
  { english: "Talking about learning a new language", japanese: "新しい言語の学習について話す" },
  { english: "A conversation in a clothing store", japanese: "洋服店での会話" },
  { english: "Discussing goals for the new year", japanese: "新年の抱負について話す" },
  { english: "At the veterinarian's office", japanese: "獣医にて" },
  { english: "Booking a flight online", japanese: "オンラインで航空券を予約する" },
  { english: "A conversation at a family dinner", japanese: "家族での夕食での会話" },
  { english: "Talking about managing stress", japanese: "ストレス管理について話す" },
  { english: "Asking a coworker about their weekend", japanese: "同僚に週末について尋ねる" },
  { english: "At a car wash", japanese: "洗車場にて" },
  { english: "A conversation about different cultures", japanese: "異文化についての会話" },
  { english: "Giving a tour of your city to a friend", japanese: "友人に自分の街を案内する" },
];

const TOEIC_PART1_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Photograph Description #${i + 1}`,
  japanese: `写真描写問題 #${i + 1}`
}));

const TOEIC_PART2_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Question-Response #${i + 1}`,
  japanese: `応答問題 #${i + 1}`
}));

const TOEIC_PART3_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Conversation #${i + 1}`,
  japanese: `会話問題 #${i + 1}`
}));

const TOEIC_PART4_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Short Talk #${i + 1}`,
  japanese: `説明文問題 #${i + 1}`
}));

const TOEIC_PART5_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Sentence Completion #${i + 1}`,
  japanese: `短文穴埋め問題 #${i + 1}`
}));

const TOEIC_PART6_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Text Completion #${i + 1}`,
  japanese: `長文穴埋め問題 #${i + 1}`
}));

const TOEIC_PART7_TOPICS: LessonTopic[] = Array.from({ length: 50 }, (_, i) => ({
  english: `Reading Comprehension #${i + 1}`,
  japanese: `読解問題 #${i + 1}`
}));


export const CATEGORIZED_LESSONS: CategorizedLessons = {
    general: GENERAL_LESSON_TOPICS,
    business: BUSINESS_LESSON_TOPICS,
    daily: DAILY_LESSON_TOPICS,
    toeic_part1: TOEIC_PART1_TOPICS,
    toeic_part2: TOEIC_PART2_TOPICS,
    toeic_part3: TOEIC_PART3_TOPICS,
    toeic_part4: TOEIC_PART4_TOPICS,
    toeic_part5: TOEIC_PART5_TOPICS,
    toeic_part6: TOEIC_PART6_TOPICS,
    toeic_part7: TOEIC_PART7_TOPICS,
};
